### PR TITLE
Update init.sh

### PR DESCRIPTION
**Pull request by yangxyo**
## WHAT
(Write the change being made with this pull request)
Update init.sh

## WHY
(Write the motivation why you submit this pull request)
fix compinit:503: no such file or directory:  .zinit/completions/_enhancd_

### CODE REVIEW

**Comment by ulwlu** [comment]
I really want this PR merged. It's annoying.

**Comment by jorgebucaran** [comment]
Hey! @yangxyo @ulwlu Could you explain why this is needed? Also, this branch has conflicts that need to be resolved before we can merge here. Please fix them? 🙏

**Comment by ulwlu** [comment]
Hi. First of all I'm sorry for saying a word 'annoying', I love this OSS and use everyday.

### minimal reproduce

`~/.zshrc`

```zsh
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
	print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
	command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
	command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
		print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
		print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
zinit lucid for b4b4r07/enhancd

```

### cause

Zinit plugin manager handles plugin's completions by symlinking them to ${ZINIT[COMPLETIONS_DIR]} at installation.

```
~/.zinit/completions/
├── _enhancd_cd_after.fish -> /Users/kohei.murakami/.zinit/plugins/b4b4r07---enhancd/functions/_enhancd_cd_after.fish
├── _enhancd_cd_before.fish -> /Users/kohei.murakami/.zinit/plugins/b4b4r07---enhancd/functions/_enhancd_cd_before.fish
├── _enhancd_cd_builtin.fish -> /Users/kohei.murakami/.zinit/plugins/b4b4r07---enhancd/functions/_enhancd_cd_builtin.fish
├── _enhancd_command_awk.fish -> /Users/kohei.murakami/.zinit/plugins/b4b4r07---enhancd/functions/_enhancd_command_awk.fish

....
```

However, enhancd will delete fish completions if user uses zsh **after installation**.

Therefore, zinit will claim "There is no symlink of ~/.zinit/completions/_enhancd_****.fish".

To resolve this with zinit, we should keep fish completions.

### remark

I understand it will just slow non-zinit users, so not ideal way to resolve.
I'm currently just forked and using my own repository.

https://github.com/ulwlu/enhancd

**Comment by jorgebucaran** [comment]
@ulwlu We're no longer deleting Fish sources. Please upgrade to the latest Enhancd and let us know if you still have any issues! 💯 

https://github.com/b4b4r07/enhancd/blob/91c4231d50981106b44ae8d31583796640375ce4/init.sh#L23-L74

**Comment by ulwlu** [comment]
@jorgebucaran 
Oh I see!
Thank you very much!

**Pull request closed without merging**
