### PR TITLE
Rename init.sh to  enhancd.plugin.zsh

### PR DESCRIPTION
**Pull request by CHNB128**
## WHAT
Rename init.sh to  enhancd.plugin.zsh

## WHY
To compatibility with antigen zsh plugin manager

### CODE REVIEW

**Comment by b4b4r07** [comment]
Thank you for pull request.

But it cannot be merged because enhancd is not only zsh plugin but also bash etc

**Comment by CHNB128** [comment]
You may create duplicated file with name I suggest to add zsh (antigen) support

**Comment by b4b4r07** [comment]
Having symbolic link to init file etc is fine.

**Comment by CHNB128** [comment]
Cool, hope you will care that. 
Thanks for you attention.

**Comment by b4b4r07** [comment]
Could you give me a pull request for that when you have time? Thanks!

**Comment by CHNB128** [comment]
Yes, this one #116

**Comment by b4b4r07** [comment]
#116 has been merged so closing this

**Pull request closed without merging**
