### PR TITLE
Prevent deletion of directories named `src` 😱

### PR DESCRIPTION
**Pull request by sirlantis**
The `init.fish` script deletes `$path/src` - by default `$path` is `.`, which
means it will actually delete folders named `src` in the directory the shell
is opened in.

Let's just delete the `init.fish` file, which will make fish look in `conf.d/` instead,
where the `conf.d/enhanced.fish` file will be found, which doesn't have that problem.

### CODE REVIEW

**Comment by Gazorby** [comment]
init.fish is intended to be used by oh-my-fish framework, wich provides $path variable holding the plugin installation path. So only src/ under script location should be deleted. How did you installed enhancd ?

**Comment by sirlantis** [comment]
Using fundle.

**Comment by Gazorby** [comment]
See the readme, only fisher and oh-my-fish are supported to install enhancd on fish shell

**Comment by b4b4r07** [comment]
This should be written in README as a caution?

**Comment by sirlantis** [comment]
Or should we maybe get rid of the deletion code? TBH I was really suprised to see "rm" being called from a plug-in init script.

**Comment by Gazorby** [comment]
Yes, but we could also bring fundle compatibility by not deleting bash sources on a fish install (so we wouldn't the `$path`  variable)

**Comment by Gazorby** [comment]
I'll submit another PR for this later

**Comment by jorgebucaran** [comment]
This PR removes the top-level `init.fish` file, but we already took care of it in 7085570, so the work is done.

> @sirlantis Or should we maybe get rid of the deletion code? TBH I was really suprised to see "rm" being called from a plug-in init script.

We moved to `enhancd_uninstall`, so it will only run when you uninstall Enhancd with `fisher remove enhancd`.


https://github.com/b4b4r07/enhancd/blob/91c4231d50981106b44ae8d31583796640375ce4/conf.d/enhancd.fish#L43-L64

**Pull request closed without merging**
